spring.application.name=restaurant-service

spring.config.import=optional:configserver:http://host.docker.internal:8888

spring.datasource.url=jdbc:mysql://host.docker.internal:3306/restaurant_db
spring.datasource.username=root
spring.datasource.password=808812@Ma

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

eureka.client.service-url.defaultZone=http://host.docker.internal:8761/eureka/